
version: "3"
services:
    ddclient:
        image: linuxserver/ddclient
        container_name: ddclient
        tty: true
        stdin_open: true
        environment:
            - PUID: 1000
            - PGID: 1000
            - TZ: Europe/London
        volumes:
            - ./ddclient.conf:/config/ddclient.conf
        restart: unless-stopped